blank_issues_enabled: true
contact_links:
  - name: Question / discussion
    url: https://github.com/tomoyukioya/FileHistoryClone/discussions
    about: For questions and general discussion, please use Discussions instead of Issues.
